server:
  port: 9090

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id : PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/product-service-fallback
        - id: SHOPPING-CART-SERVICE
          uri: lb://SHOPPING-CART-SERVICE
          predicates:
            - Path=/shopping-carts/**
          filters:
            - name: CircuitBreaker
              args:
                name: SHOPPING-CART-SERVICE
                fallbackuri: forward:/shopping-cart-service-fallback